create table if not exists public.coupons (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  is_claimed boolean not null default false,
  code text not null,
  claimed_by text null,
  claimed_at timestamp with time zone null,
  constraint coupons_pkey primary key (id),
  constraint coupons_code_key unique (code)
) TABLESPACE pg_default;

create index IF not exists idx_coupons_is_claimed on public.coupons using btree (is_claimed) TABLESPACE pg_default;